no-permissions-error: "&4&l(!)&c You do not have permission to do this."
console-error: "&4&l(!)&c Only players can execute this command."
invalid-player-error: "&4&l(!)&c A valid player must be provided."
argument-error: "&4&l(!)&c A valid amount of arguments must be provided! Usage: <usage>"

CommandHead:
  head-message: "&6&l(!)&e You have received the player head of <player>&e."

CommandHub:
  hub-message: "&6&l(!)&e Teleporting to &e&lHub&e..."
  spawn-message: "&6&l(!)&e Teleporting to &e&lSpawn&e..."

CommandBack:
  back-error: "&4&l(!)&c There is no stored location for you to teleport back to."
  back-message: "&6&l(!)&e Teleporting to your last location..."

CommandHome:
  home-null-error: "&4&l(!)&c You do not have a home set."
  home-exists-error: "&4&l(!)&c You already have a home. Use /deletehome before setting a new one."
  home-deleted-message: "&6&l(!)&e Your home has been deleted."
  home-created-message: "&6&l(!)&e Your home has been set to your current coordinates."
  home-teleport-message: "&6&l(!)&e Teleporting to your home..."

