no-permissions-error: "&4&l(!)&c You do not have permission to do this."
console-error: "&4&l(!)&c Only players can execute this command."
invalid-player-error: "&4&l(!)&c A valid player must be provided."
argument-error: "&4&l(!)&c A valid amount of arguments must be provided! Usage: <usage>"

CommandHead:
  head-message: "&6&l(!)&e You have received the player head of <player>&e."

CommandHat:
  hat-error: "&4&l(!)&c Air cannot be set as a hat."
  hat-message: "&6&l(!)&e Your hat has been set."
  hat-sender-message: "&6&l(!)&e The hat of <player>&e has been set."

CommandRename:
  rename-error: "&4&l(!)&c You must have an item in your hand to rename."
  rename-message: "&6&l(!)&e Your main hand item has been renamed."

CommandHub:
  block-error: "&4&l(!)&c You can not modify blocks within 50 blocks of spawn."
  hub-message: "&6&l(!)&e Teleporting to &e&lHub&e..."
  spawn-message: "&6&l(!)&e Teleporting to &e&lSpawn&e..."

CommandBack:
  back-error: "&4&l(!)&c There is no stored location for you to teleport back to."
  back-message: "&6&l(!)&e Teleporting to your last location..."

CommandHome:
  home-null-error: "&4&l(!)&c You do not have a home set."
  home-exists-error: "&4&l(!)&c You already have a home. Use /deletehome before setting a new one."
  home-deleted-message: "&6&l(!)&e Your home has been deleted."
  home-created-message: "&6&l(!)&e Your home has been set to your current coordinates."
  home-teleport-message: "&6&l(!)&e Teleporting to your home..."

CommandWarp:
  permission-error: "&4&l(!)&c You do not have permission to teleport to this warp."
  warp-null-error: "&4&l(!)&c There is no set warp with the name provided."
  warp-exists-error: "&4&l(!)&c A warp with this name already exists!"
  warp-message: "&6&l(!)&e Teleporting to warp &e&l<warp>&e..."
  warp-set-message: "&6&l(!)&e The warp been set to your current location."
  warp-deleted-message: "&6&l(!)&e The warp &e&l<warp>&e has been deleted."

CommandRandomTeleport:
  randomteleport-message: "&6&l(!)&e Teleporting to coordinates <coordinates>&e..."
