name: OptimalPlugin
version: 1.0
author: RySty
main: optimalplugin.OptimalPlugin
api-version: 1.15

commands:
  head:
    aliases: [playerhead]
  hat:
  rename:
  hub:
  spawn:
  back:
  home:
  deletehome:
    aliases: [delhome]
  sethome:
  warp:
  deletewarp:
    aliases: [delwarp]
  setwarp:
  randomteleport:
    aliases: [rtp]
